<a href="https://colab.research.google.com/github/Ayush114131516/my-new-repo/blob/main/carPrice_estimation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/car_data.csv')
df.sample(5)

name  year  selling_price  \
3042              Hyundai Santro Magna AMT BSIV  2019         400000   
3322  Toyota Innova 2.5 Z Diesel 7 Seater BS IV  2014        1050000   
2903                            Maruti Alto LXi  2012         150000   
3048           Maruti Eeco CNG 5 Seater AC BSIV  2019         470000   
309                  Tata Tiago 1.2 Revotron XZ  2019         425000   

      km_driven    fuel seller_type transmission         owner  
3042      16000  Petrol  Individual    Automatic   First Owner  
3322      97000  Diesel  Individual       Manual  Second Owner  
2903      50000  Petrol  Individual       Manual   First Owner  
3048      10000     CNG  Individual       Manual   First Owner  
309       19600  Petrol  Individual       Manual   First Owner

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   name           4340 non-null   object
 1   year           4340 non-null   int64 
 2   selling_price  4340 non-null   int64 
 3   km_driven      4340 non-null   int64 
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB


In [ ]:
print(df['year'].value_counts())
print(df['fuel'].value_counts())
print(df['seller_type'].value_counts())
print(df['transmission'].value_counts())
print(df['owner'].value_counts())

2017    466
2015    421
2012    415
2013    386
2014    367
2018    366
2016    357
2011    271
2010    234
2019    195
2009    193
2008    145
2007    134
2006    110
2005     85
2020     48
2004     42
2003     23
2002     21
2001     20
1998     12
2000     12
1999     10
1997      3
1996      2
1995      1
1992      1
Name: year, dtype: int64
Diesel      2153
Petrol      2123
CNG           40
LPG           23
Electric       1
Name: fuel, dtype: int64
Individual          3244
Dealer               994
Trustmark Dealer     102
Name: seller_type, dtype: int64
Manual       3892
Automatic     448
Name: transmission, dtype: int64
First Owner             2832
Second Owner            1106
Third Owner              304
Fourth & Above Owner      81
Test Drive Car            17
Name: owner, dtype: int64


In [ ]:
X=df.iloc[:,[1,3,4,6]].values
y=df.iloc[:,2].values
print(X)
print(y)

[[2007 70000 'Petrol' 'Manual']
 [2007 50000 'Petrol' 'Manual']
 [2012 100000 'Diesel' 'Manual']
 ...
 [2009 83000 'Petrol' 'Manual']
 [2016 90000 'Diesel' 'Manual']
 [2016 40000 'Petrol' 'Manual']]
[ 60000 135000 600000 ... 110000 865000 225000]


In [ ]:
from sklearn.preprocessing import LabelEncoder
lb1=LabelEncoder()
X[:,2]=lb1.fit_transform(X[:,2])
lb2=LabelEncoder()
X[:,3]=lb2.fit_transform(X[:,3])

In [ ]:
X

array([[2007, 70000, 4, 1],
       [2007, 50000, 4, 1],
       [2012, 100000, 1, 1],
       ...,
       [2009, 83000, 4, 1],
       [2016, 90000, 1, 1],
       [2016, 40000, 4, 1]], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
reg=RandomForestRegressor(n_estimators=300,random_state=0)
reg.fit(X_train,y_train)

RandomForestRegressor(n_estimators=300, random_state=0)

In [ ]:
print(reg.score(X_test,y_test)*100)

75.79783473129758


In [ ]:
ndata=[2017,7000,'Petrol','Manual']
ndata[2]=lb1.transform([ndata[2]])[0]
ndata[3]=lb2.transform([ndata[3]])[0]

In [ ]:
reg.predict([ndata])

array([617422.22222222])